# Use an official Node.js runtime as the base image
FROM node:22-slim

# Set the working directory in the Docker image
WORKDIR /usr/source/app

# Copy package.json to install dependencies
COPY package.json ./

# Install the project dependencies
RUN npm install
RUN npm install -g nodemon

# Copy the rest of the application code, excluding db, src, and lib
COPY . .

# Remove the db, src, server, and lib directories after copying everything else
RUN rm -rf ./database ./source ./library ./server

# Start the application using the existing start:watch script
CMD ["npm", "run", "start:watch"]